default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  statement_limit: 200

development:
  <<: *default
  host: localhost
  database: <%= ENV.fetch("DATABASE") %>
  username: <%= ENV.fetch("USERNAME") %>
  password: <%= ENV.fetch("PASSWORD") %>
  gssencmode: disable

test:
  <<: *default
  host: localhost
  database: <%= ENV.fetch("DATABASE_TEST") %>
  username: <%= ENV.fetch("USERNAME") %>
  password: <%= ENV.fetch("PASSWORD") %>
  gssencmode: disable
